import '@fortawesome/fontawesome-free/js/all';
import 'swiper/css';
import '@spectrum-web-components/tabs/sp-tabs.js';
import '@spectrum-web-components/tabs/sp-tab.js';
import '@spectrum-web-components/tabs/sp-tab-panel.js';

import './main.scss';
import './components/typography/typography.scss';
import './components/container.scss';
import './components/form/form';
import './components/header/header';
import './components/navigation/navigation';
import './components/header-banner/header-banner';
import './components/button/button';
import './components/top-brands/top-brands';
import './components/hot-categories/hot-categories';
import './components/tabs/tabs';
import './components/card/card';
import './components/popup/popup';
import './components/promo-banner/promo-banner';
import './components/best-sellers/best-sellers';
import './components/newsletter/newsletter';
import './components/test-animate/test-animate';
import './components/subscribe/subscribe';
import './components/footer/footer';
import './components/grid-system/grid-system';
import './components/social-icons/social-icons';
import './components/vertical-menu/vertical-menu';
import './components/drawer/drawer';

console.log('Hello IT-academy student 🚀');
